import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className="bg-[#000] font-gotham text-white antialiased"> */}
      <body className="bg-[#141618] font-gotham text-white antialiased">
        <div className="min-h-screen">
          <Header />
          <div className="my-8 md:my-12">{children}</div>
        </div>
      </body>
    </html>
  )
}
